### PR TITLE
Moved to TBXML+NSDictionary

### PR DESCRIPTION
**Pull request by segiddins**

### CODE REVIEW

**Comment by blakewatters** [comment]
Very nice! I think we should just make this available as RKTBXMLSerialization instead of potentially breaking anyone on the current setup. I'll push it up as a new repository and put up a deprecation notice on this repo.

**Comment by segiddins** [comment]
Sounds good!

**Comment by segiddins** [comment]
Do you want me to?

**Comment by blakewatters** [comment]
Sorry I've been slow on this. I am burning down pull requests now and will get this knocked out.

**Comment by segiddins** [comment]
OK. Give me a few minutes to fix the documentation?

**Comment by segiddins** [comment]
OK just renamed everything, should be good to go!

**Comment by kevmeyer** [comment]
is there a reason why this was never merged? The idea sounds very good to me...

**Comment by segiddins** [comment]
@kevmeyer it's available at https://github.com/blakewatters/RKTBXMLSerialization

**Pull request closed without merging**
